name: CBOM Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-cbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Or your project version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Find site-packages path
        id: find-site-packages
        run: |
          SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
          echo "site_packages=$SITE_PACKAGES" >> $GITHUB_OUTPUT

      - name: Run CBOMKit Action (Python)
        uses: PQCA/cbomkit-action@main
        env:
          CBOMKIT_PYTHON_SITE_PACKAGES: ${{ steps.find-site-packages.outputs.site_packages }}
        
